In [ ]:
postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    country;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)

In [ ]:
df.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381740.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   code             239 non-null    object
 1   name             239 non-null    object
 2   continent        239 non-null    object
 3   region           239 non-null    object
 4   surface_area     239 non-null    float64
 5   indep_year       192 non-null    float64
 6   population       239 non-null    int64
 7   life_expectancy  222 non-null    float64
 8   gnp              239 non-null    float64
 9   gnp_old          178 non-null    float64
 10  local_name       239 non-null    object
 11  government_form  239 non-null    object
 12  head_of_state    238 non-null    object
 13  capital          232 non-null    float64
 14  code2            239 non-null    object
dtypes: float64(6), int64(1), object(8)
memory usage: 28.1+ KB

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    country
    WHERE
    continent = 'Asia';
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
1,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65,AE
2,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotarjan,126,AM
3,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144,AZ
4,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149,BH

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    country
    WHERE
    continent = 'Asia'
    ORDER BY
    surface_area;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454,MO
1,MDV,Maldives,Asia,Southern and Central Asia,298.0,1965.0,286000,62.2,199.0,NaN,Dhivehi Raajje/Maldives,Republic,Maumoon Abdul Gayoom,2463,MV
2,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208,SG
3,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149,BH
4,HKG,Hong Kong,Asia,Eastern Asia,1075.0,NaN,6782000,79.5,166448.0,173610.0,Xianggang/Hong Kong,Special Administrative Region of China,Jiang Zemin,937,HK

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    country
    WHERE
    continent = 'Asia'
    ORDER BY
    surface_area DESC;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,CHN,China,Asia,Eastern Asia,9572900.0,-1523.0,1277558000,71.4,982268.0,917719.0,Zhongquo,People'sRepublic,Jiang Zemin,1891,CN
1,IND,India,Asia,Southern and Central Asia,3287260.0,1947.0,1013662000,62.5,447114.0,430572.0,Bharat/India,Federal Republic,Kocheril Raman Narayanan,1109,IN
2,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864,KZ
3,SAU,Saudi Arabia,Asia,Middle East,2149690.0,1932.0,21607000,67.8,137635.0,146171.0,Al-´Arabiya as-Sa´udiya,Monarchy,Fahd ibn Abdul-Aziz al-Sa´ud,3173,SA
4,IDN,Indonesia,Asia,Southeast Asia,1904570.0,1945.0,212107000,68.0,84982.0,215002.0,Indonesia,Republic,Abdurrahman Wahid,939,ID

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    city;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

   id            name country_code       district  population
0   1           Kabul          AFG          Kabol     1780000
1   2        Qandahar          AFG       Qandahar      237500
2   3           Herat          AFG          Herat      186800
3   4  Mazar-e-Sharif          AFG          Balkh      127800
4   5       Amsterdam          NLD  Noord-Holland      731200

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    city c
    INNER JOIN
    country ct
    ON
    c.country_code=ct.code;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

,id,name,country_code,district,population,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
1,2,Qandahar,AFG,Qandahar,237500,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
2,3,Herat,AFG,Herat,186800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
3,4,Mazar-e-Sharif,AFG,Balkh,127800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
4,5,Amsterdam,NLD,Noord-Holland,731200,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5,NL

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    city c
    INNER JOIN
    country ct
    ON
    c.country_code=ct.code
    WHERE
    continent = 'Asia';
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

,id,name,country_code,district,population,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
1,2,Qandahar,AFG,Qandahar,237500,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
2,3,Herat,AFG,Herat,186800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
3,4,Mazar-e-Sharif,AFG,Balkh,127800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
4,64,Dubai,ARE,Dubai,669181,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65,AE

In [ ]:
df = pd.read_sql(
    """
    SELECT
    *
    FROM
    city c
    INNER JOIN
    country ct
    ON
    c.country_code=ct.code
    WHERE
    continent = 'Asia' AND
    c.population > 1500000;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df.head()

,id,name,country_code,district,population,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF
1,144,Baku,AZE,Baki,1787800,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144,AZ
2,150,Dhaka,BGD,Dhaka,3612850,BGD,Bangladesh,Asia,Southern and Central Asia,143998.0,1971.0,129155000,60.2,32852.0,31966.0,Bangladesh,Republic,Shahabuddin Ahmad,150,BD
3,765,Quezon,PHL,National Capital Reg,2173831,PHL,Philippines,Asia,Southeast Asia,300000.0,1946.0,75967000,67.5,65107.0,82239.0,Pilipinas,Republic,Gloria Macapagal-Arroyo,766,PH
4,766,Manila,PHL,National Capital Reg,1581082,PHL,Philippines,Asia,Southeast Asia,300000.0,1946.0,75967000,67.5,65107.0,82239.0,Pilipinas,Republic,Gloria Macapagal-Arroyo,766,PH

In [ ]:
df_country = pd.read_sql(
    """
    SELECT
    *
    FROM
    country;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df_country.head()

,code,name,continent,region,surface_area,indep_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381740.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ

In [ ]:
df_city = pd.read_sql(
    """
    SELECT
    *
    FROM
    city;
    """,
    "postgresql://netology:NetoSQL2019@84.201.177.166:19001/world-db"
)
df_city.head()

   id            name country_code       district  population
0   1           Kabul          AFG          Kabol     1780000
1   2        Qandahar          AFG       Qandahar      237500
2   3           Herat          AFG          Herat      186800
3   4  Mazar-e-Sharif          AFG          Balkh      127800
4   5       Amsterdam          NLD  Noord-Holland      731200

In [ ]:
df_merged = df_city.merge(df_country, left_on='country_code', right_on='code', how='inner')
df_merged.head()

,id,name_x,country_code,district,population_x,code,name_y,continent,region,surface_area,indep_year,population_y,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,1,Kabul,AFG,Kabol,1780000,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,2,Qandahar,AFG,Qandahar,237500,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,3,Herat,AFG,Herat,186800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
3,4,Mazar-e-Sharif,AFG,Balkh,127800,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
4,5,Amsterdam,NLD,Noord-Holland,731200,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL

In [ ]:
import time
print(time.ctime())

Mon Mar  2 18:13:48 2026

In [ ]:
print("Hello, world!")

Hello, world!

In [ ]:
variable_name = input()
print('Вы ввели текст:', variable_name)

васька
Вы ввели текст: васька

In [ ]:
print('Как тебя зовут?')     # вывод текста

print('Привет,', input())    # ввод текста и вывод текста

Как тебя зовут?
маша
Привет, маша

In [ ]:
name_1 = input()                          # принимаем имя первого человека
print('Привет,', name_1, '!')             # делаем первый вывод

name_2 = input()                          # принимаем имя второго человека
print('Здравствуйте,', name_2, '.')       # делаем второй вывод

билл
Привет, билл !
саша
Здравствуйте, саша .

In [ ]:
a = input()
b = input()
c = input()

print(a, b, c)

пермь
москва
челябинск
пермь москва челябинск

In [ ]:
correct_login='admin'
correct_password='pass'

In [ ]:
flag = False
for step in range(3):
    print(step)
    login = input('Введите логин')
    password = input('Введите пароль')

    if login==correct_login and password==correct_password:
      flag = True
      break

if flag==True:
    print('Добро пожаловать!')

else:
    print('Вход заблокирован')

0
Введите логинhjdhbfhb
Введите парольhhgvhgd
1
Введите логинhuefbugyf
Введите парольhdwvygdv
2
Введите логинhxvshvy
Введите парольhgwevf
Вход заблокирован